### PR TITLE
Hii Accept my PR

### PR DESCRIPTION
**Pull request by Sergi0456**
Hii Please Accept My PR Request

### CODE REVIEW

**Comment by ossamamehmood** [comment]
Perfect @Sergi0456 , I'll merge on the 1st of October to make your PR counted in Hacktoberfest 💯😊

**Comment by Sergi0456** [comment]
Hii Sir, How are you? . I think you merged the pull request but the pr is
not counted on my hacktoberfest profile page . Please solve my problem as
soon as possible. Thanks for your support and valuable time.

**Comment by ossamamehmood** [comment]
Hi Sergi, 

Yes, I saw that, Hacktoberfest PR count from 1st OCTOBER. Just resubmitting your PR on 1st October would be great. 

Thankyou!

**Comment by Sergi0456** [comment]
Thank You Sir, 👍..!

**Pull request merged**
