### PR TITLE
Made the required changes as per the Readme

### PR DESCRIPTION
**Pull request by shivam-jha2712**

### CODE REVIEW

**Comment by ossamamehmood** [comment]
Perfect @shivam-jha2712 , I'll merge on the 1st of October to make your PR counted in Hacktoberfest 💯😊

**Comment by shivam-jha2712** [comment]
Thanks

**Comment by ossamamehmood** [comment]
Reopen your PR to get entertain!

**Comment by shivam-jha2712** [comment]
> Reopen your PR to get entertain!

I have done it could you just look into it

**Comment by ossamamehmood** [comment]
Sure

**Pull request closed without merging**
